apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend:80']

      - job_name: 'backend'
        static_configs:
          - targets: ['backend:8000']

      - job_name: 'postgresql'
        static_configs:
          - targets: ['db:5432']
